/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabTestingReportingRole;

import Business.EcoSystem;
import userinterface.NurseRole.*;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Donor_NurseTakeBloodWorkRequest;
import userinterface.LabAssistantRole.*;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.Lab_TestBloodWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class LabTestingReportingProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Lab_TestBloodWorkRequest request;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public LabTestingReportingProcessWorkRequestJPanel(JPanel userProcessContainer, Lab_TestBloodWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receptionistAppointmentTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        donorFutureEligbilityifNoWhyTxtField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        donorNameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DonorRegIDTxtField = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 614, -1, -1));

        jLabel1.setText("(Result)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));
        add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 90, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 614, -1, -1));

        receptionistAppointmentTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Reg.ID", "DonorName", "MobileNo."
            }
        ));
        jScrollPane1.setViewportView(receptionistAppointmentTable2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 161, 661));

        jLabel2.setFont(new java.awt.Font("Apple Chancery", 3, 18)); // NOI18N
        jLabel2.setText("Laboratory Testing -Reporting WorkArea");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel33.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel33.setText("To be Filled by Lab Physician");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel34.setText("Does donor has any below medical problem(s) as specified below: ");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel35.setText("Sexually Transmitted Diesease (STD)");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel36.setText("Hepatitis B virus (HBV) ");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jLabel37.setText("Human immunodeficiency virus (HIV) ");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel38.setText("Hepatitis C virus (HCV) ");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        jLabel39.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel39.setText("Blood Sample Test Report");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jLabel40.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel40.setText("Is the donar eligible for future blood donation : ");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        jLabel41.setText("If No, why?");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));
        add(donorFutureEligbilityifNoWhyTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 376, -1));

        jLabel42.setText("Blood Type");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel43.setText("RH Factor");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        donorNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorNameTxtFieldActionPerformed(evt);
            }
        });
        add(donorNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 152, 27));

        jLabel3.setText("Donor Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        jLabel4.setText("Donor RegID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));
        add(DonorRegIDTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 152, 27));

        jLabel44.setText("Human T-lymphotropic virus (HTLV)");
        add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabTestingReportingWorkAreaJPanel dwjp = (LabTestingReportingWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        request.setTestBlood(resultJTextField.getText());
        request.setStatus("Completed");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void donorNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorNameTxtFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DonorRegIDTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField donorFutureEligbilityifNoWhyTxtField;
    private javax.swing.JTextField donorNameTxtField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable receptionistAppointmentTable2;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
