/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LaboratoryManagement;

/**
 *
 * @author rajusingh
 */
public class LabTestingReportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabTestingWorkArea
     */
    public LabTestingReportWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        donorFutureEligbilityifNoWhyTxtField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        donorNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DonorRegIDTxtField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 3, 18)); // NOI18N
        jLabel1.setText("Laboratory Testing -Reporting WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 24, -1, -1));

        jLabel33.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel33.setText("To be Filled by Lab Physician");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 66, -1, -1));

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel34.setText("Does donor has any below medical problem(s) as specified below: ");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 194, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 244, -1, -1));

        jLabel35.setText("Sexually Transmitted Diesease (STD)");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 248, -1, -1));

        jLabel36.setText("Hepatitis B virus (HBV) ");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 293, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 289, -1, -1));

        jLabel37.setText("Human immunodeficiency virus (HIV) ");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 332, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 328, -1, -1));

        jLabel38.setText("Hepatitis C virus (HCV) ");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 371, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 367, -1, -1));

        jLabel39.setText("Human T-lymphotropic virus (HTLV)");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 410, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 406, -1, -1));

        jLabel40.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel40.setText("Is the donar eligible for future blood donation : ");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 476, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 476, -1, -1));

        jLabel41.setText("If No, why?");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 521, -1, -1));
        add(donorFutureEligbilityifNoWhyTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 521, 376, -1));

        jLabel42.setText("Blood Type");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 137, -1, -1));

        jLabel43.setText("RH Factor");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 137, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 133, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 133, -1, -1));

        donorNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorNameTxtFieldActionPerformed(evt);
            }
        });
        add(donorNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 132, 152, 27));

        jLabel2.setText("Donor Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 137, -1, -1));

        jLabel3.setText("Donor RegID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 171, -1, -1));
        add(DonorRegIDTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 166, 152, 27));
    }// </editor-fold>//GEN-END:initComponents

    private void donorNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorNameTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DonorRegIDTxtField;
    private javax.swing.JTextField donorFutureEligbilityifNoWhyTxtField;
    private javax.swing.JTextField donorNameTxtField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    // End of variables declaration//GEN-END:variables
}
