/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorManagement;

import Business.Donor.Donor;
import Business.Donor.DonorDirectory;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rajusingh
 */
public class DonorDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorDirectory_Test
     */
    private DonorDirectory donorDirectory;
    private JPanel userProcessContainer;
    private static int Flag=0;

    public DonorDirectoryJPanel(JPanel userProcessContainer, DonorDirectory donorDirectory) {
        initComponents();
        this.donorDirectory = donorDirectory;
        this.userProcessContainer = userProcessContainer;
        //donorDirectory.eraseDonor();
        if(Flag==0){
        scanDonor();
        Flag++;
        }
        populateAppointmentTable();
        //System.out.println(donorDirectory.getDonorDirectory().get(0).getLastName());
    }

//    public DonorDirectoryJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory) {
//        this.donorDirectory=donorDirectory;
//        this.userProcessContainer=userProcessContainer;
//        populateAppointmentTable();
//        
//    }
    public void populateAppointmentTable() {
        
        DefaultTableModel dTM = (DefaultTableModel) receptionistAppointmentTable2.getModel();
        dTM.setRowCount(0);

        for (Donor d : donorDirectory.getDonorDirectory()) {

            Object row[] = new Object[3];
            row[0] = d;
            row[1] = d.getFirstName();
            row[2] = d.getMobileNo();

            dTM.addRow(row);
        }
    }

    public void scanDonor() {
        String csvFile = "/Users/rajusingh/NetBeansProjects/aed_fall_2016_project_sameer_suman_001289666/MyDatabank/Data for array.txt";
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ",";
        try {
            br = new BufferedReader(new FileReader(csvFile));
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        try {
            while ((line = br.readLine()) != null) {

                // use comma as separator
                String[] country = line.split(cvsSplitBy);
                Donor d = donorDirectory.addDonor();
                d.setLastName(country[0]);
                d.setFirstName(country[1]);
                d.setMiddleName(country[2]);
                d.setMobileNo(country[3]);
            }

        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void Search(String s) {
        TableModel vT = receptionistAppointmentTable2.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(vT);
        receptionistAppointmentTable2.setRowSorter(sorter);
        String text = searchTxtField.getText();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
            receptionistAppointmentTable2.clearSelection();
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            } catch (PatternSyntaxException pse) {
                pse.printStackTrace();
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        receptionistAppointmentTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        firstNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nationIDTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        streetAddTextArea = new javax.swing.JTextArea();
        zipPostalTxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        occupationTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        regIDTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        dOBDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        searchTxtField = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        viewDonor = new javax.swing.JButton();
        addressTypeComboBox = new javax.swing.JComboBox<>();
        nationalIDComboBox = new javax.swing.JComboBox<>();
        ethnicityComboBox = new javax.swing.JComboBox<>();
        maritalComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        mobileTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        donorPresenceStatusTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        donationStatusTxtField = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        searchDonor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        bloodPressureTxtField = new javax.swing.JTextField();
        weightTxtField = new javax.swing.JTextField();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        deferredWhyTxtField = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        heightTxtField = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lastAppointmentTxtField = new javax.swing.JTextField();
        lastDonationTxtField = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        previousDeferralTxtField = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        previousDonationReportTxtField = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        majorAlignmentTxtField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        donorFutureEligbilityifNoWhyTxtField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();

        receptionistAppointmentTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Reg.ID", "DonorName", "MobileNo."
            }
        ));
        jScrollPane1.setViewportView(receptionistAppointmentTable2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Last");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel1.add(lastNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 87, -1));
        jPanel1.add(firstNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 83, -1));

        jLabel2.setText("First");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel3.setText("Middle");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));
        jPanel1.add(middleNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 90, -1));

        jLabel5.setText("NationalID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(nationIDTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 87, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel9.setText("Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel10.setText("Street");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel11.setText("Zip/Postal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel12.setText("State/Province");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel13.setText("City");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel14.setText("Country");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jCheckBox1.setText("Preferred");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        streetAddTextArea.setColumns(20);
        streetAddTextArea.setRows(5);
        jScrollPane2.setViewportView(streetAddTextArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 277, -1));
        jPanel1.add(zipPostalTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 78, -1));

        cityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 78, -1));
        jPanel1.add(countryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 111, -1));
        jPanel1.add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 94, -1));

        jLabel16.setText("Birth Date");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLabel17.setText("Marital");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel18.setText("Ethnicity");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jLabel19.setText("Email ID");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        emailTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 110, -1));

        jLabel20.setText("Occupation");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));
        jPanel1.add(occupationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 110, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel22.setText("Personal Information");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, 20));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel23.setText("Reg.ID");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));
        jPanel1.add(regIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 96, -1));

        jLabel29.setFont(new java.awt.Font("Apple Chancery", 2, 18)); // NOI18N
        jLabel29.setText("Donate Blood & Make the Difference");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));
        jPanel1.add(dOBDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 140, 20));

        jLabel53.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel53.setText("To be Filled by Receptionist");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel54.setText("Gender");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 10));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, 20));

        searchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 90, -1));

        jLabel55.setText("Appointment scheduled for:");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        viewDonor.setText("View Donor");
        viewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonorActionPerformed(evt);
            }
        });
        jPanel1.add(viewDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 130, -1));

        addressTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(addressTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        nationalIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(nationalIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        ethnicityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ethnicityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        maritalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(maritalComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        jLabel21.setText("Mobile No.");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));
        jPanel1.add(mobileTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 110, -1));

        jLabel4.setText("Presence Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, 20));
        jPanel1.add(donorPresenceStatusTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 90, -1));

        jLabel6.setText("Donation Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, 20));
        jPanel1.add(donationStatusTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 90, -1));

        jLabel60.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel60.setText("To be Filled by Donor");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        searchDonor.setText("Search Donor");
        searchDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDonorActionPerformed(evt);
            }
        });
        jPanel1.add(searchDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jTabbedPane1.addTab("Donor Profile", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Any Major Alignment");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel25.setText("Blood Pressure");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel27.setText("Vaccination Taken in Last  6months ");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel30.setText("Weight");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        jLabel44.setText("General Health/Are you feeling well?");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel45.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel45.setText("If Deferred, why?");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));
        jPanel2.add(bloodPressureTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 96, -1));

        weightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTxtFieldActionPerformed(evt);
            }
        });
        jPanel2.add(weightTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 96, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        jLabel46.setText("lbs");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        jLabel26.setText("mmHg");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel28.setFont(new java.awt.Font("Apple Chancery", 3, 18)); // NOI18N
        jLabel28.setText("Current Medical and Physical Body Status ");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 6, -1, -1));
        jPanel2.add(deferredWhyTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 344, -1));

        jLabel47.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel47.setText("Deferred/NotDeferred Status");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jLabel48.setText("Height");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        heightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTxtFieldActionPerformed(evt);
            }
        });
        jPanel2.add(heightTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 96, -1));

        jLabel50.setText("inches");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jLabel52.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel52.setText("System Generated");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel49.setText("Last Appointment, if any");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel2.add(lastAppointmentTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 190, -1));
        jPanel2.add(lastDonationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 190, -1));

        jLabel56.setText("Last Donation, if any");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel2.add(previousDeferralTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, -1));

        jLabel57.setText("Previous Deferral, if any?");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel58.setText("Previous Donation Report");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel2.add(previousDonationReportTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, -1));

        jLabel59.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel59.setText("To be Filled by Nurse");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel31.setText("If yes, what");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));
        jPanel2.add(majorAlignmentTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 180, -1));

        jTabbedPane1.addTab("Current Medical Status", jPanel2);

        jLabel32.setFont(new java.awt.Font("Apple Chancery", 3, 18)); // NOI18N
        jLabel32.setText("Blood Test Report");

        jLabel33.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel33.setText("To be Filled by Lab Physician");

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel34.setText("Does donor has any below medical problem(s) as specified below: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel35.setText("Sexually Transmitted Diesease (STD)");

        jLabel36.setText("Hepatitis B virus (HBV) ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel37.setText("Human immunodeficiency virus (HIV) ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel38.setText("Hepatitis C virus (HCV) ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel39.setText("Human T-lymphotropic virus (HTLV)");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel40.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel40.setText("Is the donar eligible for future blood donation : ");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel41.setText("If No, why?");

        jLabel42.setText("Blood Type");

        jLabel43.setText("RH Factor");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(124, 124, 124)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(124, 124, 124)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(124, 124, 124)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(124, 124, 124)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(124, 124, 124)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(donorFutureEligbilityifNoWhyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel34))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel32))
                    .addComponent(jLabel33))
                .addGap(330, 330, 330))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel34)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(donorFutureEligbilityifNoWhyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtFieldActionPerformed

    private void emailTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtFieldActionPerformed

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        String query = searchTxtField.getText().toLowerCase();
        Search(query);
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    private void viewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonorActionPerformed

        int selectedRow = receptionistAppointmentTable2.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select any row to get details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            // Setting value in corresponding fields
            // Donor Profile

            Donor d = (Donor) receptionistAppointmentTable2.getValueAt(selectedRow, 0);
            lastNameTxtField.setText(d.getLastName());
            firstNameTxtField.setText(d.getFirstName());
            middleNameTextField.setText(d.getMiddleName());
            nationIDTxtField.setText(d.getNationID());
            streetAddTextArea.setText(d.getStreetAddress());
            zipPostalTxtField.setText(d.getZipPostal());
            cityTxtField.setText(d.getCity());
            stateTxtField.setText(d.getStateProvince());
            countryTxtField.setText(d.getCountry());
            emailTxtField.setText(d.getEmailID());
            mobileTxtField.setText(d.getMobileNo());
            occupationTextField.setText(d.getOccupation());
            donorPresenceStatusTxtField.setText(d.getDonorPresenceStatus());
            donationStatusTxtField.setText(d.getDonationStatus());

            //Nurse Assesment
            majorAlignmentTxtField.setText(d.getAnyMajorAlignmentWhat());
            bloodPressureTxtField.setText(d.getBloodPressure());
            heightTxtField.setText(d.getHeight());
            weightTxtField.setText(d.getWeight());
            deferredWhyTxtField.setText(d.getDeferredWhy());

            //LabReport
            donorFutureEligbilityifNoWhyTxtField.setText(d.getDonorFutureEligbilityifNoWhy());

        }
    }//GEN-LAST:event_viewDonorActionPerformed

    private void weightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTxtFieldActionPerformed

    private void heightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTxtFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDonorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addressTypeComboBox;
    private javax.swing.JTextField bloodPressureTxtField;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JTextField countryTxtField;
    private com.toedter.calendar.JDateChooser dOBDateChooser;
    private javax.swing.JTextField deferredWhyTxtField;
    private javax.swing.JTextField donationStatusTxtField;
    private javax.swing.JTextField donorFutureEligbilityifNoWhyTxtField;
    private javax.swing.JTextField donorPresenceStatusTxtField;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JComboBox<String> ethnicityComboBox;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField heightTxtField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastAppointmentTxtField;
    private javax.swing.JTextField lastDonationTxtField;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JTextField majorAlignmentTxtField;
    private javax.swing.JComboBox<String> maritalComboBox;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JTextField mobileTxtField;
    private javax.swing.JTextField nationIDTxtField;
    private javax.swing.JComboBox<String> nationalIDComboBox;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JTextField previousDeferralTxtField;
    private javax.swing.JTextField previousDonationReportTxtField;
    private javax.swing.JTable receptionistAppointmentTable2;
    private javax.swing.JTextField regIDTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchDonor;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JTextArea streetAddTextArea;
    private javax.swing.JButton viewDonor;
    private javax.swing.JTextField weightTxtField;
    private javax.swing.JTextField zipPostalTxtField;
    // End of variables declaration//GEN-END:variables
}
